name: Main CI Workflow

on: push

jobs:
  build-test-docker:
    name: Helm Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: helm-build-dependencies
      run: helm dep build .
    - name: helm-lint
      run:  helm lint .
